### ISSUE TITLE
Garrybrayn(jup)23

### ISSUE THREAD

**Issue by MK-ATMOSFERA** [MicrosoftDocs/intellicode#560]
**Product and Version** [VS/VSCode]:
**OS Version** [macOS/Windows]:
**IntelliCode Extension Version**: 
**Target Platform or Language** [e.g. Node.js]:

**Steps to Reproduce / Scenario:**

1.
2.

```[tasklist]
### Tasks
- [ ] https://github.com/MicrosoftDocs/intellicode/issues/322
- [ ] https://github.com/MicrosoftDocs/intellicode/issues/509
- [ ] https://github.com/MicrosoftDocs/intellicode/issues/556
- [ ] https://github.com/MicrosoftDocs/intellicode/issues/557
```
